DROP table IF EXISTS user;

CREATE TABLE  user(
    id BIGINT NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL DEFAULT '',
    password VARCHAR(255) NOT NULL DEFAULT '',
    PRIMARY KEY(id)
);

DROP table IF EXISTS post;

CREATE TABLE post(
    id BIGINT NOT NULL AUTO_INCREMENT,
    title VARCHAR(255) NOT NULL DEFAULT '',
    content LONGTEXT NOT NULL,
    created_at BIGINT NOT NULL DEFAULT 0,
    updated_at BIGINT NOT NULL DEFAULT 0,
    author_id BIGINT NOT NULL DEFAULT 0,
    category_id BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY(id)
);

DROP table IF EXISTS category;

CREATE TABLE category(
    id BIGINT NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL DEFAULT '',
    PRIMARY KEY(id)
);

DROP table IF EXISTS tag;

CREATE TABLE tag(
    id BIGINT NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL DEFAULT '',
    PRIMARY KEY(id)
);

DROP table IF EXISTS post_tag;

CREATE TABLE post_tag(
    id BIGINT NOT NULL AUTO_INCREMENT,
    post_id BIGINT NOT NULL DEFAULT 0,
    tag_id BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY(id)
);